
;;Directories
(defvar tahti-config-dir (file-name-as-directory user-emacs-directory)
  "The root dir of the Emacs configuration.")
(defvar tahti-lisp-dir (file-name-directory (locate-file "tahti-init.el" load-path))
  "This directory houses all of the initialisation modules.")
(defvar tahti-vendor-dir   (expand-file-name "vendor"   tahti-config-dir)
  "This directory houses Emacs Lisp packages that are not yet available in
ELPA (or MELPA).")
(defvar tahti-var-dir      (expand-file-name "var"      tahti-config-dir)
  "This folder houses various files saved/generated by Emacs.")
(defvar tahti-snippets-dir (expand-file-name "snippets" tahti-var-dir)
  "This folder houses addition yasnippet.")
(defvar tahti-dictionaries-dir (expand-file-name "predictive" tahti-var-dir)
  "This folder houses addition yasnippet.")
(defvar tahti-themes-dir   (expand-file-name "themes"   tahti-lisp-dir)
  "Place where addittional themes are stored")

(setq default-directory               (expand-file-name "~/")
      eshell-directory-name           (expand-file-name "eshell"     tahti-var-dir )
      semanticdb-default-save-directory (expand-file-name "semanticdb" tahti-var-dir)
      backup-directory                (expand-file-name  "backups" tahti-var-dir)
      autosave-directory              (expand-file-name  "autosave" tahti-var-dir)
      backup-directory-alist       `(("" . ,backup-directory))
      desktop-path                 `(,(expand-file-name "desktop" tahti-var-dir))
      desktop-dirname                 (expand-file-name "desktop" tahti-var-dir)
      desktop-base-file-name                            "desktop"
      desktop-menu-path            `(,(expand-file-name "desktop/menu" tahti-var-dir))
      desktop-menu-directory          (expand-file-name "desktop/menu" tahti-var-dir)
      desktop-menu-list-file                            "menu"
      desktop-menu-base-filename                        "menu-desktop"
  )


;;Files

(defconst tahti-alias-file  (expand-file-name "diralias"  tahti-config-dir)
  "File contains line separated entries of `DIR' `ALIAS'.
Neither dir nor alias may contain spaces.")
(setq tahti-locate-file      (expand-file-name "locate.db"   tahti-var-dir))
(setq recentf-save-file      (expand-file-name "recentf"     tahti-var-dir))
(setq bookmark-default-file  (expand-file-name "bookmarks"   tahti-var-dir))
(setq bc-bookmark-file       (expand-file-name "breadcrumb"  tahti-var-dir))
(setq tramp-persistency-file-name (expand-file-name "tramp"  tahti-var-dir))
(setq ido-save-directory-list-file (expand-file-name "ido"   tahti-var-dir))
(setq save-place-file        (expand-file-name "saveplace"   tahti-var-dir))  ;file to store positions in files
(setq-default woman-cache-filename (expand-file-name "woman-cache" tahti-var-dir))
(setq savehist-file          (expand-file-name "savehist"    tahti-var-dir))
(setq srecode-map-save-file  (expand-file-name "srecode-map" tahti-var-dir))
(unless (file-exists-p tahti-var-dir)
  (make-directory tahti-var-dir))
(unless (file-exists-p tahti-snippets-dir)
  (make-directory tahti-snippets-dir))
(unless (file-exists-p backup-directory)
  (make-directory backup-directory))
(unless (file-exists-p eshell-directory-name )
  (make-directory eshell-directory-name ))
(unless (file-exists-p semanticdb-default-save-directory)
  (make-directory semanticdb-default-save-directory))
(unless (file-exists-p autosave-directory)
  (make-directory autosave-directory))
(unless (file-exists-p desktop-dirname)
  (make-directory desktop-dirname))
(unless (file-exists-p desktop-menu-directory)
  (make-directory desktop-menu-directory))
(provide 'tahti-dirs)
