(defvar tahti-config-dir (file-name-directory load-file-name)
  "The root dir of the Emacs configuration.")
(defvar tahti-core-dir (expand-file-name  "core" tahti-config-dir)
  "This directory houses all of the initialisation modules.")
(defvar tahti-vendor-dir (expand-file-name "vendor" tahti-config-dir)
  "This directory houses Emacs Lisp packages that are not yet available in
ELPA (or MELPA).")
(defvar tahti-var-dir (expand-file-name "var" tahti-config-dir)
  "This folder houses various files saved/generated by Emacs.")
(defvar tahti-snippets-dir (expand-file-name "snippets" tahti-var-dir)
  "This folder houses addition yasnippet bundles distributed with Prelude.")
(defvar tahti-savefile-dir (expand-file-name "savefile" tahti-var-dir)
  "This folder stores all the automatically generated save/history-files.")
(defvar tahti-personal-dir (expand-file-name "personal" tahti-config-dir)
  "Users of Emacs are encouraged to keep their personal configuration
changes in this directory. All Emacs Lisp (*.el) files there are loaded automatically at start.")
(defvar tahti-themes-dir (expand-file-name "themes" tahti-config-dir)
  "Place where addittional themes are stored")


(defconst tahti-alias-file (expand-file-name "diralias" tahti-config-dir)
  "File contains line separated entries of `DIR' `ALIAS'.
Neither dir nor alias may contain spaces.")

;; set default directory to $HOME
(setq default-directory "~/")

(provide 'tahti-dirs)
