;;Directories
(defvar tahti-config-dir (file-name-directory load-file-name)
  "The root dir of the Emacs configuration.")
(defvar tahti-core-dir     (expand-file-name  "core"    tahti-config-dir)
  "This directory houses all of the initialisation modules.")
(defvar tahti-vendor-dir   (expand-file-name "vendor"   tahti-config-dir)
  "This directory houses Emacs Lisp packages that are not yet available in
ELPA (or MELPA).")
(defvar tahti-var-dir      (expand-file-name "var"      tahti-config-dir)
  "This folder houses various files saved/generated by Emacs.")
(defvar tahti-snippets-dir (expand-file-name "snippets" tahti-var-dir)
  "This folder houses addition yasnippet.")
(defvar tahti-personal-dir (expand-file-name "personal" tahti-config-dir)
  "Users of Emacs are encouraged to keep their personal configuration
changes in this directory. All Emacs Lisp (*.el) files there are loaded automatically at start.")
(defvar tahti-themes-dir   (expand-file-name "themes"   tahti-config-dir)
  "Place where addittional themes are stored")
;; set default directory to $HOME
(setq default-directory               (expand-file-name "~/"))
(setq ido-save-directory-list-file    (expand-file-name "ido")     tahti-var-dir)
(setq backup-directory-alist `(("" . ,(expand-file-name  "backups" tahti-var-dir))))
(setq eshell-directory-name           (expand-file-name "eshell"     tahti-var-dir ))
(setq semanticdb-default-save-directory (expand-file-name "semanticdb" tahti-var-dir))

;;Files

(defconst tahti-alias-file  (expand-file-name "diralias"  tahti-config-dir)
  "File contains line separated entries of `DIR' `ALIAS'.
Neither dir nor alias may contain spaces.")
(setq tahti-locate-file      (expand-file-name "locate.db"  tahti-var-dir)
      "File contains database of cached home directory")
(setq recentf-save-file      (expand-file-name "recentf"    tahti-var-dir))
(setq bookmark-default-file  (expand-file-name "bookmarks"  tahti-var-dir))
(setq bc-bookmark-file       (expand-file-name "breadcrumb" tahti-var-dir))
(setq tramp-persistency-file-name (expand-file-name "tramp" tahti-var-dir))
(setq save-place-file        (expand-file-name "saveplace"  tahti-var-dir))  ;file to store positions in files
(setq-default woman-cache-filename (expand-file-name "woman-cache" tahti-var-dir))
(setq savehist-file          (expand-file-name "savehist"   tahti-var-dir))
(setq srecode-map-save-file  (expand-file-name "srecode-map"tahti-var-dir))

(provide 'tahti-dirs)
